# Estágio 1: Build
FROM node:22-alpine AS build
WORKDIR /app

# Copia arquivos de dependências
COPY package*.json ./
RUN npm install

# Copia o código e gera o build de produção
COPY . .
RUN npm run build -- --configuration production

# Estágio 2: Servir com Nginx
FROM nginx:alpine
# O caminho 'browser' é comum nas versões mais recentes do Angular (v17+)
COPY --from=build /app/dist/diario-online-frontend/browser /usr/share/nginx/html

# Expõe a porta padrão do Nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
